/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.monzo.webcrawler;

import java.net.MalformedURLException;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        new App().start();
    }

    private void start() {
        System.out.println("WebCrawler0.1");
        System.out.println();

        while(true) {
            System.out.println("Insert the initial url or type exit to stop:");

            Scanner scanner = new Scanner(System.in);
            String input = scanner.nextLine().trim();

            if("exit".equalsIgnoreCase(input)) {
                System.out.println("Goodbye!");
                return;
            }

            try {
                CrawlerService crawlerService = CrawlerService.create(input);

                crawlerService.wait();

//                synchronized(crawlerService) {
//                    try {
//                        crawlerService.wait();
//                    } catch(InterruptedException e) {
//
//                    }
//                }

//                while(!crawlerService.isTerminated()) {
//                    Thread.sleep(1000);
//                }



            } catch (MalformedURLException | InterruptedException e) {
                throw new RuntimeException(e);
            }
        }
    }
}
